config/routes.rb
Rails.application.routes.draw do
	root "dynamic#home"
  get '/team', to: "static#team"
  get '/contact', to: "static#contact"
  get '/home/:first_name', to: 'dynamic#home_first_name'
  get 'gossip/:i', to: 'dynamic#one_gossip'
  get 'gossip/user/:i', to: 'dynamic#user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	validates :name, presence: true
	validates :zip_code, length: { minimum: 5}
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_table_tag_gossips
	has_many :tags, through: :join_table_tag_gossips

  validates :content, presence: true
  validates :title, presence: true

end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
	belongs_to :tag
  belongs_to :gossip
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_tag_gossips
	has_many :gossips, through: :join_table_tag_gossips
	validates :title, presence: true, uniqueness: true, length: { in: 3..15}
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "Message"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "Message"
	
	validates :first_name, presence: true
  validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_controller.rb
class DynamicController < ApplicationController
  attr_accessor :one_gossip, :gossip, :user
  def home
  	puts "@"*60
  	puts "je suis dans home du dynamicController /server /terminal"
  	puts "@"*60
    @gossip = Gossip.all
	end
	
  def one_gossip
    @one_gossip = Gossip.find_by(id: params[:i])
        @user = User.find_by(id: @one_gossip.user)

  end

  def user 
    @one_gossip = Gossip.find_by(id: params[:i])
    @user = User.find_by(id: @one_gossip.user)
  end
  


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
  	puts "@"*60
  	puts "je suis dans team / server /terminal"
  	puts "@"*60

  end

  def contact
  end

  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/dynamic/home.html.erb
<h1 class="text-primary">Bienvenue sur THE GOSSIP PROJECT</h1>


<div class="row">

<% @gossip.each do |i| %>
<div class="card col-sm-3 text-center">
  <div class="card-header">
    <p>potin n°<%= i.id %></p>
  </div>
  <div class="card-body">
    <h5 class="card-title">auteur : <%= i.user.first_name %></h5>
    <p class="card-text">titre : <%= i.title %></p>
    <a href= "gossip/<%= i.id%>" class="btn btn-primary">En savoir plus</a>
  </div>
</div>
<% end %>

</div>

app/views/dynamic/home_first_name.html.erb
<h1 class="text-center">Welcome <%= params[:first_name] %></h1>

app/views/dynamic/one_gossip.html.erb
<h1> Titre : <%= @one_gossip.title %> </h1>

<h4> Contenue :</h4>
<p> <%= @one_gossip.content %></p>
<a href = "user/<%=@user.id %>" class="btn btn-primary">voir l'auteur du potin'</a>

app/views/dynamic/user.html.erb
<h1>Nom : <%= @user.first_name%></h1>
<h1>Prénom : <%= @user.last_name%></h1>
<h3>Email : <%= @user.email %></h3>
<h3>Age: <%= @user.age %>ans</h3>
<h3>Ville: <%= @user.city.name %></h3>
<h4>Description : <%= @user.description %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THPS05J1TgpYayaGuigui</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/flatly/bootstrap.min.css">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <title class="navbar-brand">The Gossip Project</title>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <span class="nav-link"> <%= link_to "Home", root_path %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"> <%= link_to "About Us", team_path %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"> <%= link_to "Contact", contact_path %></span>
      </li>
    </ul>

  </div>
</nav>
    </header>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>